Added functionality for swowing card with all conrgatulations
OleksandrGubariev/GreetingCard pull request #22
Opened 2020-10-23 18:01 UTC by RomanKlishch

- added servlet PreviewServlet;
- added method for return card from DB;
- added test;
- added templates

2020-10-23 19:07 UTC, AlexKievDeveloper approved these changes

2020-10-24 17:56 UTC, Rooman commented
What does swowing mean?

2020-10-24 18:25 UTC, Rooman requested changes

2020-10-24 18:25 UTC, Rooman commented on src/test/java/com/greetingcard/web/servlet/card/EditCardServlet.java
> +public class EditCardServlet extends HttpServlet {
remove such code please

2020-10-24 18:25 UTC, Rooman commented on src/test/resources/testDB/migration/R__1setUpUsers.sql
> +VALUES ('null','null','null', '@null','null','null',2);
null is such a bad choice for test data

2020-10-24 18:25 UTC, Rooman commented on src/main/java/com/greetingcard/dao/jdbc/JdbcCardDao.java
> +                    int link_id = resultSet.getInt("link_id");
I'll cut your hands for such kind of mistakes. 
@AlexKievDeveloper You approved this.

2020-10-24 19:18 UTC, RomanKlishch commented on src/main/java/com/greetingcard/dao/jdbc/JdbcCardDao.java
> +                card.setCongratulationList(new LinkedList<>(congratulationMap.values()));
Я использую эту колекцию только для добавления новой линки в конец списка

2020-10-25 10:56 UTC, AlexKievDeveloper approved these changes

2020-10-26 14:19 UTC, OleksandrGubariev approved these changes

2020-10-26 14:19 UTC, merged